fabric:
  image: cloudguru/mwc:ovpn
  ports:
  - "1194:1194/udp"
  - "1194:1194/tcp"
  cap_add:
  - ALL
  labels:
    io.expeto.project: mist
    io.expeto.product: vEPC
    io.expeto.component: ovpn
    io.expeto.version: latest
    io.rancher.container.requested_ip: 10.42.11.1
  privileged: true
  restart: 'no'

