hss:
  image: cloudguru/mwc:hss
  cap_add:
  - ALL
  labels:
    io.expeto.project: mist
    io.expeto.product: vEPC
    io.expeto.component: hss
    io.expeto.version: latest
    io.rancher.container.requested_ip: 10.42.11.102
  privileged: true
  restart: 'no'